package edu.oregonstate.tuning;

/**
 * tune the parameter or choose which model generated by the Dagger framework are the best by decoding 
 * on the development set
 * 
 * @author Jun Xie (xie@eecs.oregonstate.edu)
 *
 */
public class TuningFactory {

	
}